spring:
  datasource:
    url: jdbc:mariadb://14.50.47.205:3307/crayon
    driver-class-name: org.mariadb.jdbc.Driver
    username: dev
    password: se7enngiths
    hikari:
      pool-name: jpa-hikari-pool
      maximum-pool-size: 5
      jdbc-url: ${spring.datasource.url}
      username: ${spring.datasource.username}
      password: ${spring.datasource.password}
      driver-class-name: ${spring.datasource.driver-class-name}
      data-source-properties:
        rewriteBatchedStatements: true
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        jdbc.batch_size: 1000
        format_sql: true
        show_sql: true
        use_sql_comments: true
    defer-datasource-initialization: true
  data:
#    mongodb:
#      host: mongodb
#      port: 27017
#      authentication-database: admin
#      database: crayon
#      username: root
#      password: "se7enngiths"
  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
    port: 6379
    host: redis
    password: "1q2w3e4r"
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# cors 설정
cors:
  allowed-origins: "*"
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  max-age: 3600

logging:
  level:
    root: info
    org:
      hibernate: info
