pipeline {
    agent any
    stages {
        stage('CLONE') {
            steps {
                git branch: 'build_be', credentialsId: 'credential_Id', url: 'https://lab.ssafy.com/s08-final/S08P31B203.git'
            }
        }

        stage('BUILD') {
            steps {
                sh '''
                cd back-end/coldcrayon
                chmod +x gradlew
                ./gradlew clean build
                '''
            }
        }
        stage('DOCKER BUILD') {
            steps
            {
                cd back-end/cold/crayon
                sh "pwd"
                sh "docker build -t gmkim716/crayon-spring-container ."
            }
        }

        stage('DEPLOY') {
            steps {
            sh '''
            echo 'delete previous spring-container'
            docker stop crayon-spring-container
            docker rm crayon-spring-container
            docker run -d -p 8080:8080 --name crayon-spring-container gmkim716/crayon-spring-container
            echo 'Success'
            '''
            }
        }
    }
}

