pipeline {
    agent any
    stages {
        stage('CLONE') {
            steps {
                git branch: 'build_be', credentialsId: 'credential_Id', url: 'https://lab.ssafy.com/s08-final/S08P31B203.git'
            }
        }

        stage('BUILD') {
            steps {
                script {
                withCredentials([string(credentialsId: 'clientId', variable: 'clientId'), string(credentialsId: 'clientSecret', variable: 'clientSecret')]) {
                        sh '''
                        cd back-end/coldcrayon/src/main/resources/
                        echo '${clientId}'
                        echo '$clientId'
                        echo '$clientId:$clientSecret > application-server.yml'
                        cat application-server.yml
                        '''
                    }
                }
                sh '''
                cd back-end/coldcrayon
                chmod +x gradlew
                ./gradlew clean build
                '''
            }
        }
        stage('DOCKER BUILD') {
            steps
            {
                sh '''
                cd ./back-end/coldcrayon
                pwd
                docker build -t gmkim716/crayon-spring-container .
                '''
            }
        }

        stage('DEPLOY') {
            steps {
            sh '''
            echo 'delete previous spring-container'
            docker stop crayon-spring-container
            docker rm crayon-spring-container
            docker run -d -p 8080:8080 --name crayon-spring-container gmkim716/crayon-spring-container
            echo 'Success'
            '''
            }
        }
    }
}

