pipeline {
    agent any
    stages {
        stage('CLONE') {
            steps {
                git branch: 'build_fe2', credentialsId: 'credential_Id', url: 'https://lab.ssafy.com/s08-final/S08P31B203.git'
            }
        }

        stage('DOCKER BUILD') {
            steps
            {
                withCredentials([file(credentialsId: 'frontEnv', variable: 'env')]) {
                    script {
                        sh 'chmod 755 front/.env'
                        sh 'cp $env front/.env'
                        sh '''
                        cd  front/
                        cat .env
                        ls -al
                        '''
                    }
                }

                sh '''
                echo 'docker build dir ' ${PWD}
                cd front
            
                docker stop crayon-next-container || true
                docker rm crayon-next-container || true
                
                
                docker rmi gmkim716/crayon-next-container || true
                echo 'Remove if gmkim716/crayon-next-container exist'
                
                docker build -t gmkim716/crayon-next-container .
                '''
            }
        }

        stage('DEPLOY') {
            steps {
            sh '''
            echo 'delete previous crayon-next-container'
            # docker stop crayon-next-container
            # docker rm crayon-next-container
            docker run -d -p 3002:3000 --name crayon-next-container gmkim716/crayon-next-container
            echo 'Success: next'
            '''
            }
        }
    }
}

