pipeline {
    agent any
    stages {
        stage('CLONE')
        {
            steps{
                git branch : 'build_fe2', credentialsId : '	credential_Id', url : 'https://lab.ssafy.com/s08-final/S08P31B203.git'
            }
        }

        stage('BUILD')
        {
            steps
            {
                sh '''
                chmod +x gradlew
                ./gradlew clean build
                '''
            }
        }
        stage('DOCKER BUILD')
        {
            steps
            {
                sh "docker build -t gmkim716/crayon-spring-container ."
            }
        }

        stage('DEPLOY')
        {
            steps
            {
            sh '''
            docker run -d -p 3002:3000 --name crayon-next-container gmkim716/crayon-next-container
            echo 'Success'
            '''
            }

        }
    }
}
